### ISSUE TITLE
Component ColumnDefinition declared `PropTypes` instead of `propTypes`.

### ISSUE THREAD

**Issue by ronwillemse** [GriddleGriddle/Griddle#790] opened 2018-01-17 20:17 UTC
## Griddle version

1.11.1
--

After rendering the app the console gives the error:

Warning: Component ColumnDefinition declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?

Please fix this.

**Comment by dahlbyk** [comment] 2018-01-17 22:06
Duplicate of #786, fixed by https://github.com/GriddleGriddle/Griddle/commit/d7c058b9c713f7a1621265ed53a8bf128c7763d8 but not published yet.

**Closed by dahlbyk** 2018-01-17 22:06 UTC

**Comment by dahlbyk** [comment] 2018-02-15 14:56
1.11.2 was published this morning with this fix.
