### ISSUE TITLE
Grid not rendering - Cannot read property 'headerCssClassName' of null

### ISSUE THREAD

**Issue by bharadwajag** [GriddleGriddle/Griddle#662] opened 2017-05-08 09:32 UTC
## Griddle version
"griddle-react": "^1.3.1",
## Expected Behavior
Should render proper table
## Actual Behavior
Not rendering table, getting error 
![griddle](https://cloud.githubusercontent.com/assets/7804894/25798234/f83bb84e-33fd-11e7-8a9b-f24c787124f4.png)

## Steps to reproduce
Follow this documentation  - http://griddlegriddle.github.io/Griddle/docs/ 
Install griddle
`npm install --save griddle-react`

Here is my code 

```
import React from 'react';
import Griddle, { plugins }  from 'griddle-react';

export class DashboardPage extends React.Component { // eslint-disable-line react/prefer-stateless-function
  constructor(props) {
    super(props);
    
    // ignore these lines 
    const fromDate = new Date();
    const toDate = new Date();
    fromDate.setDate(fromDate.getDate() - 30);
    toDate.setHours(23, 59, 59, 0);
    fromDate.setHours(0, 0, 0, 0);
    this.state = {
      fromDate: fromDate,
      toDate: toDate,
    };
  }
  componentDidMount() {
    this.props.getCompanies(this.state.fromDate, this.state.toDate,this.refs.DashboardToastr);
  }
 
  onFilter = (e) => {
    const toastr = this.refs.DashboardToastr;
    this.props.getCompanies(this.state.fromDate, this.state.toDate, toastr);//Sending toastr parameter to access them in Sagas.
  }
  render() {
    const { loading, error, companies } = this.props;
    return (
           <Griddle
              data={ companies ? companies : [{}]}
              plugins={[plugins.LocalPlugin]}
            />
    );
  }
}
DashboardPage.propTypes = {
  loading: React.PropTypes.bool,
  error: React.PropTypes.oneOfType([
    React.PropTypes.object,
    React.PropTypes.bool,
  ]),
  companies: React.PropTypes.oneOfType([
    React.PropTypes.array,
    React.PropTypes.bool,
    React.PropTypes.object
  ]),
  getCompanies: React.PropTypes.func,
};
export function mapDispatchToProps(dispatch) {
  return {

    getCompanies: (fromDateObj, toDateObj, toastr) => {
      let fromDate = moment(fromDateObj).format(DATE_FORMAT);
      let toDate = moment(toDateObj).format(DATE_FORMAT);
      dispatch(loadCompanies({ fromDate, toDate, toastr }))
    },
  };
}
const mapStateToProps = createStructuredSelector({
  companies: makeSelectCompanies(),
  loading: makeSelectLoading(),
  error: makeSelectError(),
});
// Wrap the component to inject dispatch and state into it
export default connect(mapStateToProps, mapDispatchToProps)(DashboardPage);

```

## Pull request with failing test or storybook story with issue

While this step is not necessary, a failing test(s) and/or a [storybook story](https://github.com/storybooks/react-storybook) will help us resolve the issue much more easily. Please see the README for more information.

**Comment by bharadwajag** [comment] 2017-05-09 04:49
@ryanlanciaux
Could you please help on this issue, am I doing something wrong here?
I've followed the documents - http://griddlegriddle.github.io/Griddle/docs/ but no use.
Note : Its working fine in - "griddle-react": "^0.8.1".

**Comment by dahlbyk** [comment] 2017-05-09 23:31
Try installing the latest version? I'm not able to reproduce this, and I can't see how `cellProperties` on the [failing line](https://github.com/GriddleGriddle/Griddle/blob/e9ecd87e8b6c3ee9c4df1346517f5e211b78e703/src/plugins/local/components/TableHeadingCellContainer.js#L55) could be `null` given [its implementation](https://github.com/GriddleGriddle/Griddle/blob/e9ecd87e8b6c3ee9c4df1346517f5e211b78e703/src/selectors/dataSelectors.js#L290-L294).

**Comment by bharadwajag** [comment] 2017-05-10 05:09
@dahlbyk 
Thanks for the reply will try to install the latest version as you suggested. 
Right now I'm using - "griddle-react": "^1.3.1", is not the latest?

**Comment by dahlbyk** [comment] 2017-05-10 13:55
> Right now I'm using - "griddle-react": "^1.3.1", is not the latest?

`"griddle-react": "^1.5.0"` is available, but not marked `@latest` yet.

**Comment by dahlbyk** [comment] 2017-05-10 13:58
(I'm 99% certain what you're seeing will have been fixed by https://github.com/GriddleGriddle/Griddle/commit/dbcff1d2b0fb80ffa3db02523f08a29bb69b2a8c.)

**Comment by bharadwajag** [comment] 2017-05-11 11:52
@dahlbyk 
This issue has been fixed in the latest version - "griddle-react": "^1.5.0".  
Thanks @dahlbyk. 
But styles are not rendering - found the reason here - https://github.com/GriddleGriddle/Griddle/issues/661#issuecomment-299944751

**Closed** 2017-05-11 11:53 UTC
