### ISSUE TITLE
visible property in columnMetaData seems to have no effect

### ISSUE THREAD

**Issue by nlien** [GriddleGriddle/Griddle#114] opened 2015-03-12 16:14 UTC
Setting the visible property to false seems to have no effect when rendering the table. The column with the visible property set to false is shown anyway. Am I wrong in this?

**Comment by nextminds** [comment] 2015-03-26 09:55
Same here in version 0.2.4, downgraded to 0.2.3 and it works again.

**Comment by Jamesford** [comment] 2015-05-08 07:33
It now seems to show or hide the checkbox for hiding/showing the column under the grid's settings menu.

**Comment by anakinjay** [comment] 2015-06-02 12:42
Seconded, was tearing my hair out.  Nice to see it's not just me that it doesn't work for.

**Comment by wubenhe** [comment] 2015-06-19 20:38
The column with visible is false only have effect in the setting box, but it still shows up on the table. 
I think it could be a bug.

**Comment by Janekk** [comment] 2015-07-01 14:46
Confirmed, this looks like a bug but @nextminds 's workaround works :)

**Comment by slangeberg** [comment] 2015-08-02 19:59
:+1:  to fix this - excluding fields from the columns list also appears to exclude them from the rowData object - this is a problem, as it is common to render some fields, and not others, such as in my case, where I have a renderer on one column that is using multiple data fields.

**Comment by oskareke** [comment] 2016-03-07 11:09
Did anyone come up with an elegant solution for when you need the data of a column (for example user id) for use in another column (username that links to '/userId') but don't want the user id column to show up?

**Comment by nlien** [comment] 2016-03-07 12:13
I believe it's just a matter of using a custom component, and use this.props.rowData.userId in that component for whatever you want.

**Comment by oskareke** [comment] 2016-03-07 13:05
That's what I'm currently doing but I'd like the userId column to be hidden. Like @slangeberg described, excluding fields from the columns list also appears to exclude them from the rowData object. 

So, the question is how to get access to the this.props.rowData.userId property (or an alias thereof) in the custom component without having a userId column?

**Comment by nlien** [comment] 2016-03-08 10:37
I've made a fiddle for demonstrating what I mean. I don't see the problem by accessing the userId prop from the rowData object, even when excluding it from the columns list.
[https://jsfiddle.net/inillie/m374gnxd/](url)

**Comment by gidili** [comment] 2016-04-11 16:14
@nlien thanks this helped! 👍

**Comment by oskareke** [comment] 2016-04-11 16:28
@nlien Helped me too, thanks! :+1:

**Comment by orangecoding** [comment] 2016-05-21 08:48
this bug is being open over a year now. What about a fix?

**Comment by ryanlanciaux** [comment] 2016-05-21 18:13
@orangecoding please feel free to submit a PR and we will get if merged. Thanks

**Comment by orangecoding** [comment] 2016-05-21 18:47
@ryanlanciaux
Sorry i thought this project is actively maintained ;)

**Comment by aikonplus** [comment] 2017-01-08 23:37
guys, please fix this... :/

**Comment by ryanlanciaux** [comment] 2017-02-20 11:34
We have changed the API a bit in the latest version but this should not be an issue. Thank you for the discussion here but closing this one for now -- please feel free to open a new issue if any problems are encountered 👍

**Closed by ryanlanciaux** 2017-02-20 11:34 UTC
