### ISSUE TITLE
Columns don't update

### ISSUE THREAD

**Issue by hackhat** [GriddleGriddle/Griddle#635] opened 2017-04-09 19:57 UTC
## Griddle version

1.2.0

## Expected Behavior

I should see the column b and hide column a.

## Actual Behavior

Column a is visible, but column b is not.

## Steps to reproduce

 - Set data `[{a:5}]` and column defs `[{id:'a'}]`;
 - Set data `[{b:5}]` and column defs `[{id:'b'}]`;

**Comment by dahlbyk** [comment] 2017-04-09 20:12
AFAIK, column defs are only processed when the component is initialized. Try using `actions.toggleColumn` on 'a' and 'b' instead?

**Comment by hackhat** [comment] 2017-04-09 20:28
So every time you need a different set of data you need to re init the component? Ok, I will try your suggestion.

**Comment by hackhat** [comment] 2017-04-09 20:34
Thanks anyway for you help. I can't figure out how to use `actions.toggleColumn` but changing the key property on the `<Griddle/>` is enough to refresh the columns. Strange way of handling data changes. I didn't expected that it caches the column definitions, at least not from a react component.

**Comment by dahlbyk** [comment] 2017-04-09 23:33
Can you provide a more complete example of the code you expect to work? The row/col definitions are processed into `renderProperties` of the initial state for the Redux store ([code](https://github.com/GriddleGriddle/Griddle/blob/6bb688a4921bcdde7616432b2e255379f12c14cf/src/index.js#L94-L117)). This seems a reasonable optimization to me, given that grids are typically used to render data with consistent shape.

**Comment by hackhat** [comment] 2017-04-10 16:33
@dahlbyk I guess you could check whenever the column definitions are the same? That would be a simple array check.

**Comment by sww314** [comment] 2017-07-16 13:04
Duplicate of #671

**Closed by sww314** 2017-07-16 13:04 UTC
Labels: duplicate, enhancement
