### ISSUE TITLE
Inconsistent results with filter control

### ISSUE THREAD

**Issue by ryexley** [GriddleGriddle/Griddle#123] opened 2015-04-03 20:43 UTC
My team noticed an issue today with the filtering functionality of this component. The best way I could think of to communicate the issues was with a series of screenshots. See below.

Here is the default state of the grid with no filter applied. Note that company with the name "Acuity Insurance" in the list:

![default-state](https://cloud.githubusercontent.com/assets/173844/6988442/78caf06e-da1f-11e4-9cfb-30dfcde75134.png)

When I enter the first two characters of the company name into the filter, "Acuity Insurance" is still in the list of results in the grid:

![two-character-filter](https://cloud.githubusercontent.com/assets/173844/6988449/95d6d4fc-da1f-11e4-810c-350c66f50353.png)

Now, when I enter a third charter, which, note, is still part of the company name "Acuity Insurance", I see no results at all in the grid (note that it actually does appear that there _is_ a row in the grid...but there is no content visible in it...part of the problem?):

![third-character](https://cloud.githubusercontent.com/assets/173844/6988461/af0035fe-da1f-11e4-9374-6c9ae84fff36.png)

If I enter the entire first word of the company name, "acuity" and add a question mark to the end of the word...I still have no results, but I now actually get the "no data" message in place of the grid:

![full-word-with-question-mark](https://cloud.githubusercontent.com/assets/173844/6988482/e1841dce-da1f-11e4-8e8e-1d73936a5dfb.png)

Then if I hit backspace, and remove the question mark, I actually now see the result I expect:

![backspace-remove-question-mark](https://cloud.githubusercontent.com/assets/173844/6988495/fd837ea2-da1f-11e4-84b6-620636338421.png)

Anyone else seen this? Is there a solution or workaround for fixing this? Would love to see consistent results with the filter control.

**Comment by ryanlanciaux** [comment] 2015-04-04 04:08
Hey there! Sorry you're encountering issues like this. Screen shots are a perfect way to convey this information. Are you using infinite scrolling and is this a local data set or is it calling out to a server to get results? 

We'll try to get this sorted out. :+1:

**Comment by ryexley** [comment] 2015-04-06 16:20
I am using infinite scrolling, yes...and the data is local. I am making a server call to get the results, but...prior to rendering the grid, so, its all local.

**Comment by blkmutt** [comment] 2015-04-06 17:04
Would you be able to get us some sample data to reproduce the results you're seeing?

**Comment by ryexley** [comment] 2015-04-06 17:58
The results that the above screenshots are based on is just some mock data that is getting generated...so the issues really apply to just about any data...here's a sample collection of mock data that got generated today...hopefully this helps.

https://gist.github.com/ryexley/ef7ac617ba01ebef3276

**Comment by ryanlanciaux** [comment] 2015-04-07 04:03
Thanks for posting the information. Sorry to keep bugging you for more info but could you please create a project that I can pull down to demonstrate this or something along those lines (jsfiddle or would be great too)? I'm not able to reproduce the issue and I'd really like for this to be working for you.

**Comment by ryanlanciaux** [comment] 2015-04-25 20:08
Hey @ryexley -- I'm going to close this one for now. Please let me know if you're still encountering problems and we can open it back up.

**Closed by ryanlanciaux** 2015-04-25 20:08 UTC

**Comment by ryexley** [comment] 2015-04-25 21:15
I am still experiencing it, but I've not had the capacity to put together a
full sample project to reproduce the issue. I provided a collection of
sample data, but not a full solution.

**Comment by ryanlanciaux** [comment] 2015-04-25 21:30
Thanks for sending the mock data. I was not able to reproduce the issue with the mock data.

**Comment by pherris** [comment] 2015-05-12 15:55
@ryexley are you using a custom component to render the column? the sorting/filtering only works on the raw data you pass in, not the data that is rendered.

**Comment by ryexley** [comment] 2015-05-12 17:01
@pherris not for the Company column, no...for the other column, yes, I'm using a custom component for it...but not Company.
