### ISSUE TITLE
Griddle Column is not re-rendering

### ISSUE THREAD

**Issue by sansetty2510** [GriddleGriddle/Griddle#820] opened 2018-06-21 10:27 UTC
## Griddle version
1.11.1
## Expected Behavior
Need to see the updated new columns
## Actual Behavior
Not updating the new columns
## Steps to reproduce
I am creating the Column dynamically like i am looping through one column array
In some cases like on click on some button i am updating the column array on that time component render method is re-rendering and I am seeing the the updated column name in looping to create the dynamic columns, but problem is it's not reflecting in the DOM.

**Comment by dahlbyk** [comment] 2018-06-21 13:48
Closing as duplicate of https://github.com/GriddleGriddle/Griddle/issues/671. There's some discussion over there as to how this might be supported; currently Griddle only parses `RowDefinition` and `ColumnDefinition`s on initialization: https://github.com/GriddleGriddle/Griddle/blob/caff6351694e5572bb1198a0fdfb6d617f0c1b05/src/utils/initializer.js#L32-L33.

**Closed by dahlbyk** 2018-06-21 13:48 UTC
