### ISSUE TITLE
[Discussion] Change Griddle's internal store name

### ISSUE THREAD

**Issue by ryanlanciaux** [GriddleGriddle/Griddle#647] opened 2017-04-21 14:44 UTC
We should consider changing the Griddle store name to be 'griddle' (as a default -- this name should be a prop) instead of using the default 'store'. This store is for griddle's internal state management but causes trouble when people are building custom components and want to `connect` to their app's store. There is a work around right now that I'm using in some of my apps where I build an HoC to pass 'store' as a prop to the custom component but this is perhaps not as clear as it could be?

This is a breaking change and should cause a bump in major version if we go this route because anyone that has a custom component / plugin that connects on 'store' to get Griddle's data would have to take action to work with this change.

**Comment by dahlbyk** [comment] 2017-04-22 03:27
Could the store name prop be introduced now, defaulting to 'store', to give folks a chance to update their plugins and custom components to not depend on a hard-coded value?

**Comment by ryanlanciaux** [comment] 2017-04-22 15:47
This sounds like a better path here.

**Comment by joellanciaux** [comment] 2017-05-15 02:20
I think that having a dynamic store context name would be a pretty slick, but I think I'm a little concerned that with would introduce an unfamiliar API into what we're currently using (heavy use of `recompose`, HoCs, etc.) -- I don't know if it's going to be as simple as swapping our current `connect` with a dynamic, context-driven one.

I was playing around with this a little earlier and it looks like having a custom name is pretty simple, but extending this to be dynamic (driven from a `context` string) was leading to some headaches.

**Comment by ryanlanciaux** [comment] 2017-05-15 12:25
Would it work with something like https://www.npmjs.com/package/react-redux-custom-store ?

**Comment by dahlbyk** [comment] 2017-05-15 21:16
Merged a few days ago: https://github.com/reactjs/react-redux/pull/695

**Comment by joellanciaux** [comment] 2017-05-16 01:19
`react-redux-custom-store` looks pretty great and is what I'm using, but that's where I'm running into composition issues. 

I wonder if that `react-redux` update will make things move a little smoother?

**Comment by joellanciaux** [comment] 2017-05-16 01:26
I put together [feature/custom-store-name](https://github.com/joellanciaux/Griddle/tree/feature/custom-store-name), which includes a hard-coded custom store name + some other updates that should likely live in another PR that I think would be nice (no longer re-keying data on every property update, which is pretty expensive + adding a bucket for extra properties on Griddle).

I'm fine holding off if we're wanting to make this more dynamic, but just wanted to show what I've been up to, specifically: https://github.com/joellanciaux/Griddle/blob/feature/custom-store-name/src/components/GriddleConnect.js

**Comment by jackgeek** [comment] 2017-06-10 11:14
I not sure you need a library other than react-redux to achieve this.

First: create your Provider using the createProvider function exported by react-redux. You can specify a storeKey.

Second: create your own connect function to use when you want to connect to griddle's store. This is dead easy, just callthe existing connect function and pass the store Key in the options parameter.

Done!

But IMHO griddle should use the app's store and not it's own store And then this wouldn't be a problem.

**Comment by jackgeek** [comment] 2017-06-10 11:59
Here is the griddle connect I have described above, taken from my own project:

```
import { connect } from 'react-redux';

export default function griddleConnect(mapStateToProps, mapDispatchToProps, mergeProps, options) {
  return connect(mapStateToProps, mapDispatchToProps, mergeProps, {
    ...options,
    storeKey: 'griddle-store'
  });
}

```

**Comment by jackgeek** [comment] 2017-06-10 18:05
Here is a couple of higher order components I use to ensure my cell contents have access to my app store.  

```
import React, { Component, PropTypes } from 'react';

/**
 * Griddle uses it's own redux store called 'store', which prevents us from
 * accessing the application store. This utility aliases the store
 * so we can restore it later.
 * This is an unfortunate limitation of Griddle that hopefully they will fix
 * in the future.  See: https://github.com/GriddleGriddle/Griddle/issues/647
 */

export default function aliasReactReduxContext({ contextPrefix = 'aliased-', storeKey = 'store', subKey } = {})
{
  return (WrappedComponent) => {
    const subscriptionKey = subKey || `${storeKey}Subscription`;
    return class AliasReactReduxContext extends Component {
      static contextTypes = {
        [storeKey]: PropTypes.object,
        [subscriptionKey]: PropTypes.object
      };
      static childContextTypes = {
        [`${contextPrefix}${storeKey}`]: PropTypes.object,
        [`${contextPrefix}${subscriptionKey}`]: PropTypes.object
      };
      getChildContext() {
        return {
          [`${contextPrefix}${storeKey}`]: this.context[storeKey],
          [`${contextPrefix}${subscriptionKey}`]: this.context[subscriptionKey]
        };
      }

      render() {
        return (
          <WrappedComponent {...this.props} />
        );
      }
    };
  };
}

```
```
import React, { Component, PropTypes } from 'react';

/**
 * Griddle uses it's own redux store called 'store', which prevents us from
 * accessing the application store. This utility restores the previously
 * aliased store.
 * This is an unfortunate limitation of Griddle that hopefully they will fix
 * in the future.  See: https://github.com/GriddleGriddle/Griddle/issues/647
 */

export default function restoreReactReduxContext({ contextPrefix = 'aliased-', storeKey = 'store', subKey } = {})
{
  return (WrappedComponent) => {
    const subscriptionKey = subKey || `${storeKey}Subscription`;
    return class AliasReactReduxContext extends Component {
      static contextTypes = {
        [`${contextPrefix}${storeKey}`]: PropTypes.object,
        [`${contextPrefix}${subscriptionKey}`]: PropTypes.object
      };
      static childContextTypes = {
        [storeKey]: PropTypes.object,
        [subscriptionKey]: PropTypes.object
      };
      getChildContext() {
        return {
          [storeKey]: this.context[`${contextPrefix}${storeKey}`],
          [subscriptionKey]: this.context[`${contextPrefix}${subscriptionKey}`]
        };
      }

      render() {
        return (
          <WrappedComponent {...this.props} />
        );
      }
    };
  };
}
```

**Comment by archy-bold** [comment] 2017-06-13 17:51
@jackgeek Thanks, this worked really well and meant I don't need to update my components to access the store from the context directly. It will do as a quick fix before the more major changes are made.

For anyone wondering how to get it to work, you can do the following:

```
render() {
   const GriddleWithContext = aliasReactReduxContext()(Griddle);

    return (
        <GriddleWithContext data={fakeData}>
            <ColumnDefinition
                id="id"
                title="My Title"
                customComponent={restoreReactReduxContext()(CustomComponent)} />
        </GriddleWithContext>
    );
}
```

**Comment by hackhat** [comment] 2017-07-13 11:56
Here is my workaround:

  // Import the Provider
  import {Provider} from 'react-redux';
  class Comp extends React.Component {
    static contextTypes = {
      // Request for the store
      store: PropTypes.object.isRequired,
    };
    render() {
      const HomeworkHeadingComponent = (publicProps) => {
        // Use provider with custom store from `this.context.store`
        return (
          <Provider store={this.context.store}>
            <Button>
              {title}
            </Button>
          </Provider>
        );
      };
    }
  }

**Comment by ryanlanciaux** [comment] 2017-08-11 11:07
Started working on this here https://github.com/GriddleGriddle/Griddle/pull/715

**Closed** 2017-08-22 13:23 UTC
Labels: discussion, enhancement

**Comment by peroperje** [comment] 2017-09-14 19:29
Could you explain how to use this, please?
I try to dispatch custom own action from ColumnDefinition->customComponent
but I got an error

(anonymous function)
node_modules/griddle-react/dist/module/plugins/local/selectors/localSelectors.js:152
  149 | /** Gets the current page of data
  150 |  */
  151 | var currentPageDataSelector = exports.currentPageDataSelector = (0, _reselect.createSelector)(sortedDataSelector, pageSizeSelector, currentPageSelector, function (sortedData, pageSize, currentPage) {
> 152 |   return sortedData.skip(pageSize * (currentPage - 1)).take(pageSize);
  153 | });
  154 | 
  155 | /** Get the visible data (and only the columns that are visible)
....
How can I get access to the app store(and dispatch) inside Griddle?

**Comment by archy-bold** [comment] 2017-10-03 17:39
I see this got merged. I upgraded to v 1.9.0 but I seem to be running into some problems with the store. Sometimes the griddle store seems to be getting passed to my own components. Is there something I should be doing to get this to work?

**Comment by bristoljon** [comment] 2017-10-30 15:05
Me too, I have (want) a custom `connect`'ed RowComponent that is receiving the griddle state rather than my store state. On version `1.9.0`

I'm not sure having a different store name is really the right way to go either. Redux is supposed to be the sole source of truth for the app after all. Wouldn't it make more sense to allow a configurable location in the existing redux store for storing the griddle state. Similar to how `redux-form` integrates.

e.g. 
```
import { reducer as griddle } from 'griddle-react'

export default combineReducers({
  ...,
  griddle,
})
```
Then in the Griddle render you could pass the key for where the table should expect to keep it's state in the store...

```
return (<Griddle
    data={data}
    storeKey="griddle"
  />)
```

Then internally you could use HOC's to connect the table to it's state?

**Comment by dahlbyk** [comment] 2017-10-31 03:18
There are two parts to using the current implementation:

1. Direct Griddle to avoid hiding the default store: either specify a `storeKey` for each `<Griddle>` instance, or set `Griddle.storeKey` globally (c.f. https://github.com/GriddleGriddle/Griddle/pull/751)
2. Use the appropriate `connect`:
   * To have a component access your app's default store:
      ```
      import { connect } from 'react-redux';
      ```
   * To have a custom Griddle component access its `<Griddle>`'s store:
      ```
      import { connect } from 'griddle-react';
      ```

You can see this in action [here](https://github.com/GriddleGriddle/Griddle/blob/81f8fdbad924fdcb64992d33792766f2fbf96edb/stories/index.tsx#L844-L893) (note use of `reduxConnect`, imported from `react-redux`, compared with plain Griddle `connect` for other stories' custom Griddle components).

cc @peroperje  @archy-bold 

---------------------------

> Redux is supposed to be the sole source of truth for the app after all.

I'm sure you'll find varying opinions on this, but I would say Redux is supposed to be the sole source of truth for *application state*, which doesn't necessarily encompass view state like grid pagination and form inputs. That's not to say you can't use Redux for these things, but it's far from universal.

> Wouldn't it make more sense to allow a configurable location in the existing redux store for storing the griddle state. Similar to how `redux-form` integrates.

Though Griddle obviously requires Redux to work, it seems reasonable that it should Just Work™️ when used in an app that doesn't otherwise use Redux. So _requiring_ `redux-form`-style integration seems a non-starter.

More generally, though, important extensibility comes from having a store per instance: plugins are able to modify `initialState` and provide their own `reducers`. I'm not sure how to achieve this plugin pattern with a single store, short of putting per-instance reducers into Redux (which breaks serializability).

**Comment by bristoljon** [comment] 2017-10-31 09:28
Cheers for quick and detailed explanation, @dahlbyk. I was thinking the redux integration could be optional i.e. use built in Provider if no key specified but can see how that would lead to more complications. I hadn't thought about the benefits of per instance stores regarding plugins etc. either so totally see the reasoning. And pleased to see the solution is pretty straight forward.

**Comment by jjmax75** [comment] 2018-08-08 18:11
https://stackoverflow.com/a/33633850/1377969

Dev tools are breaking for us on pages using griddle. Apparently this is due to multiple stores.

Is it possible to set griddle to use the main store?

**Comment by jjmax75** [comment] 2018-08-09 05:10
Hi,

Thanks for the quick reply.

When I go to a vote that uses griddle the Dev tools stop updating and
sometimes, not always so difficult to debug, the app crashes. The crash
only happens on screens with griddle when Redux Dev tools are also open.
I'll try to recreate and post the error message but it's fairly cryptic :D

I'm working on a team that is using griddle on a project and I've seen the
crashes myself when working so have started investigating why. I've been
told by another team member that this is an issue with Dev tools when there
are multiple stores present in an app.

So if that's true this isn't an issue with Griddle but I'm looking at
finding ways to get around the problem.

Thanks again for your time.

**Comment by dahlbyk** [comment] 2018-08-09 19:47
@jjmax75 I don't know how the Redux dev tools work, but you might try setting `storeKey='griddle'` on a Griddle component and see if that fixes the crash. (Note any custom Griddle components will need to use `import { connect } from 'griddle-react'` instead of `import { connect } from 'react-redux` to access the Griddle store.)

I don't have high hopes, since that really just changes the context key the store is saved to, but it might help?

**Comment by jjmax75** [comment] 2018-08-09 21:46
I'll give that a try thanks.

I'm not sure how is setup in the app, didn't get a chance to work on it
today, but I'll try that and let you know if it helps.

I'll also try to reproduce the crash and pussy what I find.

**Comment by slow89** [comment] 2018-08-17 22:07
@jjmax75  I had the same issue when redux dev tool was set to "Autoselect instances".  From the dropdown (top right of window) select the store you care about and the tool is stable.

**Comment by aaronsmulktis** [comment] 2021-11-18 18:06
thank you @dahlbyk !!! importing `connect` from `griddle-react` fixed my issue
