### ISSUE TITLE
rowData is empty when using customComponent

### ISSUE THREAD

**Issue by mkotar** [GriddleGriddle/Griddle#184] opened 2015-07-16 14:13 UTC
I have a strange problem in one instance of Griddle that I am using in my project: this.props.rowData is empy ;-)

Griddle Version:
"griddle-react": "^0.2.13"

here is the code:
## data source

[{
  title: 'string',
  description: 'string',
  status:'string',
  id:'string',
  creator: 'string'
}, 
{...},...]
## Main Component

class TasksGrid extends React.Component {
    constructor(props) {
        super(props);
    }

```
render() {
    var {TasksStore} = this.props.store;
    var columnsMetaData = [{
            columnName: 'id',
            displayName: '',
            store: TasksStore,
            customComponent: GridCustomButtons
        },{
            columnName: 'description',
            displayName: 'Description'
        },{
            columnName: 'status',
            displayName: 'Status'
        },{
            columnName: 'creator',
            displayName: 'Creator'
        }];

    return (
        <div>
            <Paper zDepth={2}>
                <div className="tasksGrid">
                    <Griddle
                        results={TasksStore.userTasks}
                        columns={['title', 'description', 'status', 'creator', 'id']}
                        columnMetadata={columnsMetaData}
                        useGriddleStyles={false}
                        showSetting={true}
                        sortAscendingComponent={<span className="fa fa-sort-alpha-asc"></span>}
                        sortDescendingComponent={<span className="fa fa-sort-alpha-desc"></span>}
                        />
                </div>
            </Paper>
        </div>
    );
}
```

}
## Custom Component

class GridCustomButtons extends React.Component { 

```
constructor(props) {
    super(props);
}
```

render() {
        var id = this.props.data,  // this works fine 
            rowData = this.props.rowData; // THIS IS EMPTY
            TasksStore = this.props.metadata.store; // this works fine

```
    return (
        <div>testing</div>
    );
}
```

}

Moreover if I put another column in  
 columns={[ 'NOT_EXISTING_IN_DATA_COLUMN', 'title', 'description', 'status', 'creator', 'id']}

then I will have
 this.props.rowData.NOT_EXISTING_IN_DATA_COLUMN = undefined

Does anybody know how to solve this issue?

**Comment by aindlq** [comment] 2015-07-22 16:05
I can confirm the same behavior. I've traced it down to this two lines 
https://github.com/GriddleGriddle/Griddle/blob/master/scripts/gridRow.jsx#L79
https://github.com/GriddleGriddle/Griddle/blob/master/scripts/gridRow.jsx#L81

The problem is that Object.create copies values into prototype, and _.default treat this new object as empty one.

Simple solution is to replace Object.create with _.clone. Any ideas when something can go wrong with this solution, if no I'm willing to provide a pull-request.

**Comment by ocorpening** [comment] 2015-09-22 19:55
actually I get best results with replacing it with _.extend, this copies the properties into the object not the prototype which appears to be the intention.

**Comment by TomOlivier** [comment] 2015-09-29 08:06
Having the same issue. Working great with _.extend.

**Comment by ichbinedgar** [comment] 2015-10-16 15:51
Thanks :+1:

**Comment by damassi** [comment] 2015-10-19 21:59
Will this fix be merged in soon?

**Comment by Sburke0708** [comment] 2015-10-27 16:52
Any update on the merge process?

**Comment by ryanlanciaux** [comment] 2017-02-20 11:39
This should be fixed. Please feel free to open a new issue if any problems are encountered. 👍

**Closed by ryanlanciaux** 2017-02-20 11:39 UTC
