### ISSUE TITLE
Warning: Component ColumnDefinition declaredPropTypesinstead ofpropTypes. Did you misspell the property assignment?

### ISSUE THREAD

**Issue by owen8505** [GriddleGriddle/Griddle#792] opened 2018-01-31 20:10 UTC
## Griddle version
1.11.1

## Expected Behavior
No console errors

## Actual Behavior
It looks there is a misspelling using ColumnDefinition Component, I always get this `Warning: Component ColumnDefinition declaredPropTypesinstead ofpropTypes. Did you misspell the property assignment?` in console.

## Steps to reproduce
Import ColumnDefinition and use it in any table.

## Pull request with failing test or storybook story with issue
<img width="644" alt="screen shot 2018-01-31 at 14 07 34" src="https://user-images.githubusercontent.com/3031245/35645050-4af67c80-0690-11e8-86e3-f988adcf3862.png">

**Comment by dahlbyk** [comment] 2018-02-01 04:46
Duplicate of #786, fixed by https://github.com/GriddleGriddle/Griddle/commit/d7c058b9c713f7a1621265ed53a8bf128c7763d8 but not published yet.

**Closed by dahlbyk** 2018-02-01 04:46 UTC

**Comment by dahlbyk** [comment] 2018-02-15 14:56
1.11.2 was published this morning with this fix.
