### ISSUE TITLE
Collumn selection from settings not persisting on page change

### ISSUE THREAD

**Issue by davidlashlee** [GriddleGriddle/Griddle#152] opened 2015-05-05 19:58 UTC
if griddle is setup to use external data & if you customize which columns show up via settings button.
when you click next page the columns that are displayed are reverted to the default visible columns.

even the second example on http://griddlegriddle.github.io/Griddle/externalData.html has this issue.

shoot me a line if you need any more info,

Thanks,
David Lashlee

**Comment by ThePainnn** [comment] 2015-08-06 12:51
+1 on this one

Got the same issue in my project which is based on your example for external data

**Comment by jjstrat3** [comment] 2016-01-05 18:16
+1.  This is has been a long-standing issue on our project as well.  We've actually talked about just using Facebook's data table and adding our own components to that since Griddle's "everything and the kitchen sink" appoach doesn't allow for much customization to address different use cases.  I brought up this issue in #113 , as the fix for that issue seems to have created this regression.

**Comment by ryanlanciaux** [comment] 2016-01-06 12:23
Thanks for adding more information about the cause of this issue. We will take a look.

Also, I agree about making things easier to customize. A big aspect of the changes for Griddle 1.0 is to  allow more fine-grained customization -- [see the 1.0 discussion issue](https://github.com/GriddleGriddle/Griddle/issues/276) for more info on that. We haven't really announced this because there isn't much documentation around using the new stuff (outside of pulling down the griddle-docs project and running it locally) but we have the alpha of 1.0 is in npm -- `npm install griddle-react@alpha`. 

In the new version, all of the components used by Griddle are overridable (the defaults are exported too so if you simply need to wrap functionality around one of the internal components you can override the default with a HoC or something along those lines). The core Griddle stuff will only use whatever is provided -- the new stuff only defines the defaults. If you want to discuss that more, I'd love to chat more about it in the [1.0 thread](https://github.com/GriddleGriddle/Griddle/issues/276) :+1:

**Comment by ryanlanciaux** [comment] 2017-02-20 03:27
I know it's been over a year but we have released a version of Griddle that allows this customization we've been working towards. Additionally, the state management is a lot more consistent.

Closing for now but please feel free to open a new issue if problems are encountered. 👍

**Closed by ryanlanciaux** 2017-02-20 03:27 UTC
