### ISSUE TITLE
Choppy Infinite scrolling over table elements in Chrome

### ISSUE THREAD

**Issue by astrism** [GriddleGriddle/Griddle#171] opened 2015-06-16 23:39 UTC
When using the demos(and in my own code) I experience choppy, momentum-less infinite scrolling. I've noticed if I scroll with my cursor over the data table it's choppy, but if I hold my cursor over the scrollbar it scrolls normally. Firefox scrolls normally in all cases.

I'm still looking for a workaround, only thing that works for me so far is to set `pointer-events` to `none` on the `td` elements, but this is not a real solution of course. Anyone else experience this or have any insight?

OSX Chrome Version 43.0.2357.124 (64-bit)

**Comment by astrism** [comment] 2015-06-17 21:02
I'm able to workaround this issue by setting `transform: translate3d(0px,0px,0);` on the div containing the table with the style below, it doesn't run as well as FF but 95% there.
```
.griddle-body > div > div {
  transform: translate3d(0px,0px,0);
}
```

**Comment by catalinmiron** [comment] 2015-06-22 08:21
:+1: Same thing goes for me, it fells choppy.

**Comment by legomind** [comment] 2016-01-03 22:27
Chrome works fine for me on my mac, however I have this issue when using safari. @astrism: the css you suggested does not work for me.

**Comment by ryanlanciaux** [comment] 2016-01-04 02:42
Hmm I wonder if we're somehow re-rendering on mouseover. I'll ping this thread when we have the 1.0alpha examples online -- I would like to make sure we don't have any known performance bottlenecks for the 1.0 actual release. Thanks!

**Comment by legomind** [comment] 2016-01-09 04:31
No, that is not the case from what I can see. I think for some reason just modifying the dom elements is all it take to interrupt the scrolling in some browsers.

Here are the browsers that scroll just fine for me:
```
Chrome Version 49.0.2614.0 canary (64-bit) Mac & Windows
Chrome Version 47.0.2526.106 (64-bit) Mac & Windows
Chrome for Android
Microsoft Edge 20.10240 (yuck!)
Internet Explorer 11 (double yuck!)
```

**Comment by legomind** [comment] 2016-01-09 04:45
Now I am not so sure about my last comment. I just noticed that positioning the cursor directly over the scrollbar in safari allows for smooth scrolling. :confused:

**Comment by gregvenech** [comment] 2016-03-23 20:15
I'm having the same issue...

@astrism's css did help. The issue seems to be caused by updating the existing rows instead of adding rows? Is there any way to turn this off?

I'm on version 0.4.1 installed via `npm`. (thanks for the lib btw it's great)

**Comment by ryanlanciaux** [comment] 2017-02-26 03:44
Sorry -- I realize this is from some time ago but this should no longer be an issue in Griddle 1.0 with the virtual scrolling plugin. Closing for now but please feel free to open an issue if any problems are encountered. 👍

**Closed by ryanlanciaux** 2017-02-26 03:44 UTC
